return {
	{
		id = 1,
		nameId = 99400001,
		type = 1,
		upgrade = "+%s",
		display = {
			1,
		},
		iconPath = "TP_New/Bag_item_res/Frames/iconEquipBlueprints_png",
		level = 1,
		cost = 1,
		effectType = 11,
		effectDisplay1 = {
			100,
		},
		effectDisplay2 = {},
		effectDisplay3 = {},
		effectDisplay4 = {},
		effectDisplay5 = {},
		effectDisplay6 = {},
		effectDisplay7 = {},
		effectDisplay8 = {},
		effectDisplay9 = {},
		effectDisplay10 = {},
	},
	{
		id = 2,
		nameId = 99400002,
		type = 1,
		upgrade = "+%s",
		display = {
			50,
			100,
			150,
		},
		iconPath = "TP_New/Bag_item_res/Frames/iconEquipBlueprints_png",
		level = 3,
		cost = 1,
		effectType = 1,
		effectDisplay1 = {
			0,
			50,
			0,
			0,
		},
		effectDisplay2 = {
			0,
			100,
			0,
			0,
		},
		effectDisplay3 = {
			0,
			150,
			0,
			0,
		},
		effectDisplay4 = {},
		effectDisplay5 = {},
		effectDisplay6 = {},
		effectDisplay7 = {},
		effectDisplay8 = {},
		effectDisplay9 = {},
		effectDisplay10 = {},
	},
	[4] = {
		id = 4,
		nameId = 99400004,
		type = 1,
		upgrade = "+%s",
		display = {
			1,
			2,
			3,
		},
		iconPath = "TP_New/Bag_item_res/Frames/iconEquipBlueprints_png",
		level = 3,
		cost = 1,
		effectType = 2,
		effectDisplay1 = {
			1,
		},
		effectDisplay2 = {
			2,
		},
		effectDisplay3 = {
			3,
		},
		effectDisplay4 = {},
		effectDisplay5 = {},
		effectDisplay6 = {},
		effectDisplay7 = {},
		effectDisplay8 = {},
		effectDisplay9 = {},
		effectDisplay10 = {},
	},
	[5] = {
		id = 5,
		nameId = 99400005,
		type = 2,
		upgrade = "+%s",
		display = {
			5,
			10,
			15,
			20,
			25,
			30,
			35,
			40,
			45,
			50,
		},
		iconPath = "TP_New/Bag_item_res/Frames/iconEquipBlueprints_png",
		level = 10,
		cost = 1,
		effectType = 0,
		effectDisplay1 = {
			10014,
		},
		effectDisplay2 = {
			10015,
		},
		effectDisplay3 = {
			10016,
		},
		effectDisplay4 = {
			10017,
		},
		effectDisplay5 = {
			10018,
		},
		effectDisplay6 = {
			10014,
		},
		effectDisplay7 = {
			10015,
		},
		effectDisplay8 = {
			10016,
		},
		effectDisplay9 = {
			10017,
		},
		effectDisplay10 = {
			10018,
		},
	},
	[6] = {
		id = 6,
		nameId = 99400006,
		type = 2,
		upgrade = "+%s%%",
		display = {
			3,
			6,
			10,
		},
		iconPath = "TP_New/Bag_item_res/Frames/iconEquipBlueprints_png",
		level = 3,
		cost = 1,
		effectType = 0,
		effectDisplay1 = {
			10024,
		},
		effectDisplay2 = {
			10025,
		},
		effectDisplay3 = {
			10026,
		},
		effectDisplay4 = {},
		effectDisplay5 = {},
		effectDisplay6 = {},
		effectDisplay7 = {},
		effectDisplay8 = {},
		effectDisplay9 = {},
		effectDisplay10 = {},
	},
	[7] = {
		id = 7,
		nameId = 99400007,
		type = 2,
		upgrade = "+%s%%",
		display = {
			3,
			6,
			10,
		},
		iconPath = "TP_New/Bag_item_res/Frames/iconEquipBlueprints_png",
		level = 3,
		cost = 1,
		effectType = 0,
		effectDisplay1 = {
			10034,
		},
		effectDisplay2 = {
			10035,
		},
		effectDisplay3 = {
			10036,
		},
		effectDisplay4 = {},
		effectDisplay5 = {},
		effectDisplay6 = {},
		effectDisplay7 = {},
		effectDisplay8 = {},
		effectDisplay9 = {},
		effectDisplay10 = {},
	},
	[8] = {
		id = 8,
		nameId = 99400008,
		type = 2,
		upgrade = "+%s",
		display = {
			60,
			120,
			200,
		},
		iconPath = "TP_New/Bag_item_res/Frames/iconEquipBlueprints_png",
		level = 3,
		cost = 1,
		effectType = 0,
		effectDisplay1 = {
			10037,
		},
		effectDisplay2 = {
			10038,
		},
		effectDisplay3 = {
			10039,
		},
		effectDisplay4 = {},
		effectDisplay5 = {},
		effectDisplay6 = {},
		effectDisplay7 = {},
		effectDisplay8 = {},
		effectDisplay9 = {},
		effectDisplay10 = {},
	},
	[9] = {
		id = 9,
		nameId = 99400009,
		type = 2,
		upgrade = "+%s",
		display = {
			60,
			120,
			200,
		},
		iconPath = "TP_New/Bag_item_res/Frames/iconEquipBlueprints_png",
		level = 3,
		cost = 1,
		effectType = 0,
		effectDisplay1 = {
			10040,
		},
		effectDisplay2 = {
			10041,
		},
		effectDisplay3 = {
			10042,
		},
		effectDisplay4 = {},
		effectDisplay5 = {},
		effectDisplay6 = {},
		effectDisplay7 = {},
		effectDisplay8 = {},
		effectDisplay9 = {},
		effectDisplay10 = {},
	},
}
