return {
	{
		id = 1,
		txtId = 4,
		baseLevel = 301,
		levelUp = 1,
		effectFightId = {},
		effectBuffId = {},
		proposeLevel = 20,
	},
	{
		id = 2,
		txtId = 5,
		baseLevel = 401,
		levelUp = 1,
		effectFightId = {},
		effectBuffId = {},
		proposeLevel = 40,
	},
	{
		id = 3,
		txtId = 6,
		baseLevel = 501,
		levelUp = 1,
		effectFightId = {},
		effectBuffId = {},
		proposeLevel = 60,
	},
	{
		id = 4,
		txtId = 7,
		baseLevel = 601,
		levelUp = 1,
		effectFightId = {},
		effectBuffId = {},
		proposeLevel = 80,
	},
	{
		id = 5,
		txtId = 7,
		baseLevel = 2001,
		levelUp = 1,
		effectFightId = {},
		effectBuffId = {},
		proposeLevel = 80,
	},
	{
		id = 6,
		txtId = 7,
		baseLevel = 2101,
		levelUp = 1,
		effectFightId = {},
		effectBuffId = {},
		proposeLevel = 80,
	},
	{
		id = 7,
		txtId = 7,
		baseLevel = 2201,
		levelUp = 1,
		effectFightId = {},
		effectBuffId = {},
		proposeLevel = 80,
	},
	{
		id = 8,
		txtId = 7,
		baseLevel = 2301,
		levelUp = 1,
		effectFightId = {},
		effectBuffId = {},
		proposeLevel = 80,
	},
	{
		id = 9,
		txtId = 7,
		baseLevel = 601,
		levelUp = 1,
		effectFightId = {},
		effectBuffId = {},
		proposeLevel = 80,
	},
	{
		id = 10,
		txtId = 7,
		baseLevel = 601,
		levelUp = 1,
		effectFightId = {},
		effectBuffId = {},
		proposeLevel = 80,
	},
	{
		id = 11,
		txtId = 7,
		baseLevel = 601,
		levelUp = 1,
		effectFightId = {},
		effectBuffId = {},
		proposeLevel = 80,
	},
	{
		id = 12,
		txtId = 7,
		baseLevel = 601,
		levelUp = 1,
		effectFightId = {},
		effectBuffId = {},
		proposeLevel = 80,
	},
	{
		id = 13,
		txtId = 4,
		baseLevel = 299,
		levelUp = 0,
		effectFightId = {},
		effectBuffId = {},
		proposeLevel = 5,
	},
}
