return {
	[100000] = {
		id = 100000,
		roleTitle = "",
		roleName = "{name}",
		showText = "从本体脱落出了碎片……这似乎让本体变得无法击破。该转换狩猎目标了。",
		showTime = 999,
		next = 0,
		soundCue = "",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10501_png.idol10501_png'",
	},
	[101001] = {
		id = 101001,
		roleTitle = "海盗",
		roleName = "社畜加藤",
		showText = "这都是你们逼的！谁不知道把我们公司坑破产的就是理事会！",
		showTime = 6,
		next = 101002,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/1/Voice_NPC/Cue/01/shechujiateng_01_Cue.shechujiateng_01_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20002_png.npc20002_png'",
	},
	[101002] = {
		id = 101002,
		roleTitle = "海盗",
		roleName = "厨师戴维",
		showText = "理事会！偷走我们的工作，现在还想偷走我们的命！",
		showTime = 6,
		next = 101003,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/1/Voice_NPC/Cue/01/dibite_01_Cue.dibite_01_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20001_png.npc20001_png'",
	},
	[101003] = {
		id = 101003,
		roleTitle = "海盗",
		roleName = "社畜加藤",
		showText = "我看到直播了——他们居然在直播「剿灭」我们！真不要脸！",
		showTime = 8,
		next = 101004,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/1/Voice_NPC/Cue/01/shechujiateng_02_Cue.shechujiateng_02_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20002_png.npc20002_png'",
	},
	[101004] = {
		id = 101004,
		roleTitle = "海盗",
		roleName = "厨师戴维",
		showText = "哈！那个主持人还说什么「野生风水先生」！",
		showTime = 5,
		next = 101005,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/1/Voice_NPC/Cue/01/dibite_02_Cue.dibite_02_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20001_png.npc20001_png'",
	},
	[101005] = {
		id = 101005,
		roleTitle = "海盗",
		roleName = "厨师戴维",
		showText = "我们已经抓来拷问过了……根本就是你们理事会职员假扮的！",
		showTime = 8,
		next = 0,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/1/Voice_NPC/Cue/01/dibite_03_Cue.dibite_03_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20001_png.npc20001_png'",
	},
	[103001] = {
		id = 103001,
		roleTitle = "北冕座π星的祭主",
		roleName = "鱼啄雨",
		showText = "我……我上当了吗……？",
		showTime = 4,
		next = 103002,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xiaoyu_68_Cue.xiaoyu_68_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11202_png.idol11202_png'",
	},
	[103002] = {
		id = 103002,
		roleTitle = "复乐园理事会",
		roleName = "助手",
		showText = "1。",
		showTime = 1,
		next = 103003,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xinfeng_024_Cue.xinfeng_024_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10501_png.idol10501_png'",
	},
	[103003] = {
		id = 103003,
		roleTitle = "北冕座π星的祭主",
		roleName = "鱼啄雨",
		showText = "可是，一切都那么突然……现在的情况……到底……",
		showTime = 4,
		next = 103004,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xiaoyu_69_Cue.xiaoyu_69_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11202_png.idol11202_png'",
	},
	[103004] = {
		id = 103004,
		roleTitle = "复乐园理事会",
		roleName = "助手",
		showText = "他们想买你的本命星。你没有卖的理由。",
		showTime = 4,
		next = 103005,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xinfeng_025_Cue.xinfeng_025_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10501_png.idol10501_png'",
	},
	[103005] = {
		id = 103005,
		roleTitle = "复乐园理事会",
		roleName = "助手",
		showText = "所以，给你一个。",
		showTime = 3,
		next = 103006,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xinfeng_026_Cue.xinfeng_026_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10501_png.idol10501_png'",
	},
	[103006] = {
		id = 103006,
		roleTitle = "复乐园理事会",
		roleName = "助手",
		showText = "走吧，你不会死于癌症，但如果被当做本命星交易技术的小白鼠，那就说不定了。",
		showTime = 5,
		next = 0,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xinfeng_027_Cue.xinfeng_027_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10501_png.idol10501_png'",
	},
	[105001] = {
		id = 105001,
		roleTitle = "狂化的祭主",
		roleName = "小鱼",
		showText = "死死死死死死死死死死死——",
		showTime = 3,
		next = 105002,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xiaoyu_362_Cue.xiaoyu_362_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11202_png.idol11202_png'",
	},
	[105002] = {
		id = 105002,
		roleTitle = "狂化的祭主",
		roleName = "小鱼",
		showText = "我要给你一个恶魔看了都摇头的，糊成一团的死——",
		showTime = 5,
		next = 0,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xiaoyu_363_Cue.xiaoyu_363_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11202_png.idol11202_png'",
	},
	[105003] = {
		id = 105003,
		roleTitle = "",
		roleName = "小鱼",
		showText = "好快乐啊，操作武装的感觉好快乐……",
		showTime = 4,
		next = 105004,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xiaoyu_383_Cue.xiaoyu_383_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11202_png.idol11202_png'",
	},
	[105004] = {
		id = 105004,
		roleTitle = "",
		roleName = "{name}",
		showText = "又来了。",
		showTime = 1,
		next = 0,
		soundCue = "",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10501_png.idol10501_png'",
	},
	[106001] = {
		id = 106001,
		roleTitle = "假助手",
		roleName = "？？？",
		showText = "怎么样，星图界面还算好懂吧。",
		showTime = 3,
		next = 106002,
		soundCue = "",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10501_png.idol10501_png'",
	},
	[106002] = {
		id = 106002,
		roleTitle = "努力学习的高中生",
		roleName = "小鱼",
		showText = "我……我试试……",
		showTime = 2,
		next = 0,
		soundCue = "",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11202_png.idol11202_png'",
	},
	[106003] = {
		id = 106003,
		roleTitle = "复乐园理事会",
		roleName = "军官",
		showText = "终于抓到你们了，小东西，还挺能跑的。",
		showTime = 3,
		next = 106004,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/junguan_001_Cue.junguan_001_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20000_png.npc20000_png'",
	},
	[106004] = {
		id = 106004,
		roleTitle = "假助手",
		roleName = "？？？",
		showText = "现在还不能叫做「抓到了」。",
		showTime = 3,
		next = 106005,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xinfeng_055_Cue.xinfeng_055_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10501_png.idol10501_png'",
	},
	[106005] = {
		id = 106005,
		roleTitle = "复乐园理事会",
		roleName = "军官",
		showText = "嘿，有意思。",
		showTime = 2,
		next = 106006,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/junguan_002_Cue.junguan_002_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20000_png.npc20000_png'",
	},
	[106006] = {
		id = 106006,
		roleTitle = "复乐园理事会",
		roleName = "军官",
		showText = "为了这句挑衅，回去以后，我会在你们俩身上多玩五种拷问花样。",
		showTime = 6,
		next = 0,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/junguan_003_Cue.junguan_003_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20000_png.npc20000_png'",
	},
	[106007] = {
		id = 106007,
		roleTitle = "太空海盗",
		roleName = "老张",
		showText = "谁啊这么不长眼，被包围了还敢……\
——哦。完了。",
		showTime = 3,
		next = 106008,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/laozhang_001_Cue.laozhang_001_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20000_png.npc20000_png'",
	},
	[106008] = {
		id = 106008,
		roleTitle = "太空海盗",
		roleName = "三只耳",
		showText = "喂，老张你跑什么！",
		showTime = 2,
		next = 106009,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/sanzhier_001_Cue.sanzhier_001_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20000_png.npc20000_png'",
	},
	[106009] = {
		id = 106009,
		roleTitle = "太空海盗",
		roleName = "老张",
		showText = "是信风啊——！！",
		showTime = 2,
		next = 106010,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/laozhang_002_Cue.laozhang_002_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20000_png.npc20000_png'",
	},
	[106010] = {
		id = 106010,
		roleTitle = "太空海盗",
		roleName = "老张",
		showText = "我们小本生意，跟大人物井水不犯河水，为什么会在这里撞上信风啊——",
		showTime = 6,
		next = 0,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/laozhang_003_Cue.laozhang_003_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20000_png.npc20000_png'",
	},
	[106011] = {
		id = 106011,
		roleTitle = "太空海盗",
		roleName = "三只耳",
		showText = "OH FUCK！",
		showTime = 1,
		next = 106012,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/sanzhier_002_Cue.sanzhier_002_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20000_png.npc20000_png'",
	},
	[106012] = {
		id = 106012,
		roleTitle = "太空海盗",
		roleName = "三只耳",
		showText = "老子还活着！还活着！老子这下是「信风一招都没打死的牛逼海贼」啦！",
		showTime = 7,
		next = 106013,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/sanzhier_003_Cue.sanzhier_003_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20000_png.npc20000_png'",
	},
	[106013] = {
		id = 106013,
		roleTitle = "太空海盗",
		roleName = "卡里莫夫",
		showText = "信风老师，信风老师，我是你粉丝，能给我签个名吗？",
		showTime = 4,
		next = 106014,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/kalimofu_001_Cue.kalimofu_001_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20000_png.npc20000_png'",
	},
	[106014] = {
		id = 106014,
		roleTitle = "太空海盗",
		roleName = "卡里莫夫",
		showText = "签在……签在这条被你打飞的手臂上！",
		showTime = 4,
		next = 0,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/kalimofu_002_Cue.kalimofu_002_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20000_png.npc20000_png'",
	},
	[106015] = {
		id = 106015,
		roleTitle = "",
		roleName = "缇缇波芙",
		showText = "水逆的力量可真强，我们的聊天估计也快断连了。",
		showTime = 6,
		next = 106016,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/titibofu_62_Cue.titibofu_62_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11101_png.idol11101_png'",
	},
	[106016] = {
		id = 106016,
		roleTitle = "义人",
		roleName = "信风",
		showText = "1，杂音很多。",
		showTime = 2,
		next = 106017,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xinfeng_108_Cue.xinfeng_108_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10501_png.idol10501_png'",
	},
	[106017] = {
		id = 106017,
		roleTitle = "义人",
		roleName = "信风",
		showText = "你们战斗情况如何？",
		showTime = 2,
		next = 106018,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xinfeng_109_Cue.xinfeng_109_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10501_png.idol10501_png'",
	},
	[106018] = {
		id = 106018,
		roleTitle = "",
		roleName = "缇缇波芙",
		showText = "理事会的守卫又多又烦，不过我们应付得来。",
		showTime = 4,
		next = 106019,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/titibofu_63_Cue.titibofu_63_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11101_png.idol11101_png'",
	},
	[106019] = {
		id = 106019,
		roleTitle = "",
		roleName = "缇缇波芙",
		showText = "而且我还在战场上缴获了很不错的巧克力。正在吃呢你听咕叽咕叽……",
		showTime = 7,
		next = 106020,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/titibofu_64_Cue.titibofu_64_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11101_png.idol11101_png'",
	},
	[106020] = {
		id = 106020,
		roleTitle = "",
		roleName = "科斯明船长",
		showText = "不要担心，信风。我们没有危险，你那边才——【信号中断】",
		showTime = 5,
		next = 0,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/kesiming_052_Cue.kesiming_052_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20000_png.npc20000_png'",
	},
	[106021] = {
		id = 106021,
		roleTitle = "船员",
		roleName = "小鱼",
		showText = "呜呜……瞄准、移动、躲避……",
		showTime = 3,
		next = 106022,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xiaoyu_203_Cue.xiaoyu_203_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11202_png.idol11202_png'",
	},
	[106022] = {
		id = 106022,
		roleTitle = "义人",
		roleName = "信风",
		showText = "1",
		showTime = 1,
		next = 106023,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xinfeng_194_Cue.xinfeng_194_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10501_png.idol10501_png'",
	},
	[106023] = {
		id = 106023,
		roleTitle = "义人",
		roleName = "信风",
		showText = "感觉如何？",
		showTime = 1,
		next = 106024,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xinfeng_195_Cue.xinfeng_195_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10501_png.idol10501_png'",
	},
	[106024] = {
		id = 106024,
		roleTitle = "船员",
		roleName = "小鱼",
		showText = "我感觉……我觉得……",
		showTime = 2,
		next = 106025,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xiaoyu_204_Cue.xiaoyu_204_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11202_png.idol11202_png'",
	},
	[106025] = {
		id = 106025,
		roleTitle = "船员",
		roleName = "小鱼",
		showText = "哈哈哈哈哈哈哈哈哈哈哈哈哈！",
		showTime = 3,
		next = 106026,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xiaoyu_205_Cue.xiaoyu_205_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11202_png.idol11202_png'",
	},
	[106026] = {
		id = 106026,
		roleTitle = "义人",
		roleName = "信风",
		showText = "？",
		showTime = 1,
		next = 106027,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xinfeng_196_Cue.xinfeng_196_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10501_png.idol10501_png'",
	},
	[106027] = {
		id = 106027,
		roleTitle = "义人",
		roleName = "信风",
		showText = "小鱼，你怎么了？",
		showTime = 2,
		next = 106028,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xinfeng_197_Cue.xinfeng_197_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10501_png.idol10501_png'",
	},
	[106028] = {
		id = 106028,
		roleTitle = "船员",
		roleName = "小鱼",
		showText = "好——流——畅——啊！",
		showTime = 2,
		next = 106029,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xiaoyu_206_Cue.xiaoyu_206_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11202_png.idol11202_png'",
	},
	[106029] = {
		id = 106029,
		roleTitle = "义人",
		roleName = "信风",
		showText = "流……畅？",
		showTime = 1,
		next = 106030,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xinfeng_198_Cue.xinfeng_198_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10501_png.idol10501_png'",
	},
	[106030] = {
		id = 106030,
		roleTitle = "船员",
		roleName = "小鱼",
		showText = "什么瞄准、移动、躲避，什么「难以捉摸的共振」……！",
		showTime = 4,
		next = 106031,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xiaoyu_207_Cue.xiaoyu_207_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11202_png.idol11202_png'",
	},
	[106031] = {
		id = 106031,
		roleTitle = "船员",
		roleName = "小鱼",
		showText = "这不是超级简单的吗！一点都不「难以捉摸」呀！",
		showTime = 4,
		next = 106032,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xiaoyu_208_Cue.xiaoyu_208_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11202_png.idol11202_png'",
	},
	[106032] = {
		id = 106032,
		roleTitle = "义人",
		roleName = "信风",
		showText = "我……好像什么都还没来得及教……",
		showTime = 3,
		next = 0,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xinfeng_199_Cue.xinfeng_199_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10501_png.idol10501_png'",
	},
	[106033] = {
		id = 106033,
		roleTitle = "船员",
		roleName = "小鱼",
		showText = "哈哈哈哈哈哈哈！",
		showTime = 2,
		next = 106034,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xiaoyu_221_Cue.xiaoyu_221_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11202_png.idol11202_png'",
	},
	[106034] = {
		id = 106034,
		roleTitle = "义人",
		roleName = "信风",
		showText = "？",
		showTime = 1,
		next = 106035,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xinfeng_214_Cue.xinfeng_214_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10501_png.idol10501_png'",
	},
	[106035] = {
		id = 106035,
		roleTitle = "船员",
		roleName = "小鱼",
		showText = "重新武装的感觉——非常好！",
		showTime = 3,
		next = 106036,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xiaoyu_222_Cue.xiaoyu_222_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11202_png.idol11202_png'",
	},
	[106036] = {
		id = 106036,
		roleTitle = "船员",
		roleName = "小鱼",
		showText = "在宇宙的感觉——也很好！",
		showTime = 2,
		next = 106037,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xiaoyu_223_Cue.xiaoyu_223_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11202_png.idol11202_png'",
	},
	[106037] = {
		id = 106037,
		roleTitle = "船员",
		roleName = "小鱼",
		showText = "我觉得我——完全属于这里——！！！",
		showTime = 3,
		next = 106038,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xiaoyu_224_Cue.xiaoyu_224_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11202_png.idol11202_png'",
	},
	[106038] = {
		id = 106038,
		roleTitle = "义人",
		roleName = "信风",
		showText = "……",
		showTime = 1,
		next = 106039,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xinfeng_215_Cue.xinfeng_215_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10501_png.idol10501_png'",
	},
	[106039] = {
		id = 106039,
		roleTitle = "船员",
		roleName = "小鱼",
		showText = "我要把你们全部炸烂，全部炸烂呀——",
		showTime = 4,
		next = 0,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/xiaoyu_225_Cue.xiaoyu_225_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol11202_png.idol11202_png'",
	},
	[106040] = {
		id = 106040,
		roleTitle = "",
		roleName = "敌方频道",
		showText = "又来了一个「中枢」的走狗！",
		showTime = 2,
		next = 106041,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/difangnvA_003_Cue.difangnvA_003_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20000_png.npc20000_png'",
	},
	[106041] = {
		id = 106041,
		roleTitle = "",
		roleName = "敌方频道",
		showText = "他们这次想抢走什么？！",
		showTime = 2,
		next = 106042,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/difangnanA_001_Cue.difangnanA_001_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20000_png.npc20000_png'",
	},
	[106042] = {
		id = 106042,
		roleTitle = "",
		roleName = "敌方频道",
		showText = "我们还有什么可被抢的？",
		showTime = 2,
		next = 106043,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/difangnvB_001_Cue.difangnvB_001_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20000_png.npc20000_png'",
	},
	[106043] = {
		id = 106043,
		roleTitle = "",
		roleName = "敌方频道",
		showText = "无礼的「中枢」流氓，我要把他们的面具塞进他们的[粗口]里！",
		showTime = 5,
		next = 0,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/2/cue/difangnanA_002_Cue.difangnanA_002_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/npc20000_png.npc20000_png'",
	},
	[109001] = {
		id = 109001,
		roleTitle = "第一理事卿",
		roleName = "莎乐美",
		showText = "觐见我的资格，可不是谁都有的。",
		showTime = 5,
		next = 109002,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/1/Voice_10201/Cue/shalemei_ren__17_Cue.shalemei_ren__17_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10201_png.idol10201_png'",
	},
	[109002] = {
		id = 109002,
		roleTitle = "第一理事卿",
		roleName = "莎乐美",
		showText = "好好享受吧。",
		showTime = 2,
		next = 0,
		soundCue = "/Script/Engine.SoundCue'/Game/_Game/SoundEffects/Voice_Story/1/Voice_10201/Cue/shalemei_ren__18_Cue.shalemei_ren__18_Cue'",
		headPath = "/Script/Paper2D.PaperSprite'/Game/_Game/TP_New/IdolProfile_res/Frames/idol10201_png.idol10201_png'",
	},
}
