local SrpgController = require("Module.Srpg.SrpgController")
local PlayerSystem = require("Module.Player.PlayerSystem")
local BackpackSystem = require("Module.Backpack.BackpackSystem")
local CharacterSystem = require("Module.CharacterSystem.CharacterSystem")
local ShopSystem = require("Module.ShopSystem.ShopSystem")
local MallSystem = require("Module.ShopSystem.MallSystem")
local QuestSystem = require("Module.Quest.QuestSystem")
local ActivitySystem = require("Module.Activity.ActivitySystem")
local PickUpController = require("Module.Progress.PickUpController")
local PlotSystem = require("Module.Plot.PlotSystem")
local BuildSystem = require('Module.BuildSystem.BuildSystem')
local RedPointSystem = require('Module.RedPointSystem.RedPointSystem')
local MailController = require("Module.Mail.MailController")
local HardLevelSystem = require('Module.HardLevel.HardLevelSystem')
local BossRushController = require("Module.BossRush.BossRushController")
local GachaSystem = require('Module.Gacha.GachaSystem')
local NoticeController = require("Module.Notice.NoticeController")

local ModuleManager = BaseClass("ModuleManager", Singleton)

function ModuleManager:RegisterNetCmdController()
    self.SrpgController = SrpgController:GetInstance()
    self.PlayerSystem = PlayerSystem:GetInstance()
    self.BackpackSystem = BackpackSystem:GetInstance()
    self.CharacterSystem = CharacterSystem:GetInstance()
    self.ShopSystem = ShopSystem:GetInstance()
    self.MallSystem = MallSystem:GetInstance()
    self.QuestSystem = QuestSystem:GetInstance()
    self.ActivitySystem = ActivitySystem:GetInstance()
    self.HardLevelSystem = HardLevelSystem:GetInstance()
    self.PickUpController = PickUpController:GetInstance()
    self.PlotSystem = PlotSystem:GetInstance()
    self.BuildSystem = BuildSystem:GetInstance()
    self.RedPointSystem = RedPointSystem:GetInstance()
    self.MailController = MailController:GetInstance()
    self.BossRushController = BossRushController:GetInstance()
    self.GachaSystem = GachaSystem:GetInstance()
    self.NoticeController = NoticeController:GetInstance()
end

return ModuleManager
