// Reconstructed from proto.pb (Nornium/GHS client msg.proto)
syntax = "proto3";
package ghs;
import "server_info.proto";
import "player.proto";
import "gate.proto";
import "login.proto";
import "universe.proto";
import "card.proto";
import "event.proto";
import "mission.proto";
import "bag.proto";
import "character_list.proto";
import "shop_list.proto";
import "mall_list.proto";
import "activity_list.proto";
import "plot.proto";
import "home.proto";
import "mail_list.proto";
import "hard_level.proto";
import "total_war.proto";
import "gacha.proto";
import "order.proto";
import "gm.proto";

message Msg {
  oneof sub_msg {
    ghs.ReqPlayer req_player = 1;
    ghs.ResPlayer res_player = 2;
    ghs.ReqChangePlayerName req_change_player_name = 3;
    ghs.ResChangePlayerName res_change_player_name = 4;
    ghs.ReqChangePlayerSequenceName req_change_player_sequence_name = 5;
    ghs.ResChangePlayerSequenceName res_change_player_sequence_name = 6;
    ghs.ReqChangePlayerAvatar req_change_player_avatar = 7;
    ghs.ResChangePlayerAvatar res_change_player_avatar = 8;
    ghs.ReqPlayerReceiveLevelAward req_player_receive_level_award = 9;
    ghs.ResPlayerReceiveLevelAward res_player_receive_level_award = 10;
    ghs.ReqDailyLevelFight req_daily_level_fight = 101;
    ghs.ResDailyLevelFight res_daily_level_fight = 102;
    ghs.ReqCompleteDailyLevelFight req_complete_daily_level_fight = 103;
    ghs.ResCompleteDailyLevelFight res_complete_daily_level_fight = 104;
    ghs.ReqDailyLevelSweep req_daily_level_sweep = 105;
    ghs.ResDailyLevelSweep res_daily_level_sweep = 106;
    ghs.ReqCompletePlayerDailyMission req_complete_player_daily_mission = 107;
    ghs.ResCompletePlayerDailyMission res_complete_player_daily_mission = 108;
    ghs.ReqRefreshPlayerDailyMission req_refresh_player_daily_mission = 109;
    ghs.ResRefreshPlayerDailyMission res_refresh_player_daily_mission = 110;
    ghs.NtfPlayerDailyMissionInfo ntf_player_daily_mission_info = 111;
    ghs.ReqCompletePlayerBookMission req_complete_player_book_mission = 112;
    ghs.ResCompletePlayerBookMission res_complete_player_book_mission = 113;
    ghs.ReqPlayerPicking req_player_picking = 201;
    ghs.ResPlayerPicking res_player_picking = 202;
    ghs.ReqPlayerUniverseGrowth req_player_universe_growth = 301;
    ghs.ResPlayerUniverseGrowth res_player_universe_growth = 302;
    ghs.ReqPlayerUniverseGrowthReset req_player_universe_growth_reset = 303;
    ghs.ResPlayerUniverseGrowthReset res_player_universe_growth_reset = 304;
    ghs.ReqRecordPlayerTransformInScene req_record_player_transform_in_scene = 401;
    ghs.ResRecordPlayerTransformInScene res_record_player_transform_in_scene = 402;
    ghs.ReqRemovePlayerTransformInScene req_remove_player_transform_in_scene = 403;
    ghs.ResRemovePlayerTransformInScene res_remove_player_transform_in_scene = 404;
    ghs.NtfServerTimeOffset ntf_server_time_offset = 501;
    ghs.ReqUseGiftCode req_use_gift_code = 601;
    ghs.ResUseGiftCode res_use_gift_code = 602;
    ghs.ReqSaveData req_save_data = 901;
    ghs.ResSaveData res_save_data = 902;
    ghs.ReqUniverse req_universe = 1001;
    ghs.ResUniverse res_universe = 1002;
    ghs.ReqNewUniverse req_new_universe = 1003;
    ghs.ResNewUniverse res_new_universe = 1004;
    ghs.ReqNewUniverseSpecific req_new_universe_specific = 1005;
    ghs.ResNewUniverseSpecific res_new_universe_specific = 1006;
    ghs.ReqCompleteUniverse req_complete_universe = 1007;
    ghs.ResCompleteUniverse res_complete_universe = 1008;
    ghs.ReqUniverseFight req_universe_fight = 1009;
    ghs.ResUniverseFight res_universe_fight = 1010;
    ghs.ReqCompleteUniverseFight req_complete_universe_fight = 1011;
    ghs.ResCompleteUniverseFight res_complete_universe_fight = 1012;
    ghs.ReqBossFight req_boss_fight = 1013;
    ghs.ResBossFight res_boss_fight = 1014;
    ghs.ReqCompleteBossFight req_complete_boss_fight = 1015;
    ghs.ResCompleteBossFight res_complete_boss_fight = 1016;
    ghs.ReqUniverseChangeCharacter req_universe_change_character = 1017;
    ghs.ResUniverseChangeCharacter res_universe_change_character = 1018;
    ghs.NtfUniverseInfo ntf_universe_info = 1019;
    ghs.NtfUniverseClear ntf_universe_clear = 1020;
    ghs.NtfBossInfo ntf_boss_info = 1021;
    ghs.NtfFightInfo ntf_fight_info = 1022;
    ghs.NtfUniverseBoatEnergy ntf_universe_boat_energy = 1023;
    ghs.NtfAddRealtimeBuff ntf_add_realtime_buff = 1024;
    ghs.NtfAddForeverBuff ntf_add_forever_buff = 1025;
    ghs.NtfRemoveForeverBuff ntf_remove_forever_buff = 1026;
    ghs.NtfAddForeverFightBuff ntf_add_forever_fight_buff = 1027;
    ghs.NtfEffectTriggerBegin ntf_effect_trigger_begin = 1028;
    ghs.NtfEffectTriggerEnd ntf_effect_trigger_end = 1029;
    ghs.ReqExplore req_explore = 1101;
    ghs.ResExplore res_explore = 1102;
    ghs.ReqMainPosInteract req_main_pos_interact = 1103;
    ghs.ResMainPosInteract res_main_pos_interact = 1104;
    ghs.ReqMainPosShopBuy req_main_pos_shop_buy = 1105;
    ghs.ResMainPosShopBuy res_main_pos_shop_buy = 1106;
    ghs.ReqMainPosShopRefresh req_main_pos_shop_refresh = 1107;
    ghs.ResMainPosShopRefresh res_main_pos_shop_refresh = 1108;
    ghs.NtfMainPosInfo ntf_main_pos_info = 1109;
    ghs.NtfMainPosStateChange ntf_main_pos_state_change = 1110;
    ghs.NtfMainPosAddAttach ntf_main_pos_add_attach = 1111;
    ghs.ReqCreateChooseCard req_create_choose_card = 1201;
    ghs.ResCreateChooseCard res_create_choose_card = 1202;
    ghs.ReqChooseCard req_choose_card = 1203;
    ghs.ResChooseCard res_choose_card = 1204;
    ghs.ReqRefreshChooseCard req_refresh_choose_card = 1205;
    ghs.ResRefreshChooseCard res_refresh_choose_card = 1206;
    ghs.ReqPlaceCard req_place_card = 1207;
    ghs.ResPlaceCard res_place_card = 1208;
    ghs.ReqUpgradeCard req_upgrade_card = 1209;
    ghs.ResUpgradeCard res_upgrade_card = 1210;
    ghs.ReqDemolitionCard req_demolition_card = 1211;
    ghs.ResDemolitionCard res_demolition_card = 1212;
    ghs.ReqRecallCard req_recall_card = 1213;
    ghs.ResRecallCard res_recall_card = 1214;
    ghs.ReqReplaceCard req_replace_card = 1215;
    ghs.ResReplaceCard res_replace_card = 1216;
    ghs.ReqCreateChooseCurio req_create_choose_curio = 1217;
    ghs.ResCreateChooseCurio res_create_choose_curio = 1218;
    ghs.ReqChooseCurio req_choose_curio = 1219;
    ghs.ResChooseCurio res_choose_curio = 1220;
    ghs.ReqRefreshChooseCurio req_refresh_choose_curio = 1221;
    ghs.ResRefreshChooseCurio res_refresh_choose_curio = 1222;
    ghs.NtfAddCard ntf_add_card = 1223;
    ghs.NtfAddCurio ntf_add_curio = 1224;
    ghs.NtfAddCardsForSelect ntf_add_cards_for_select = 1225;
    ghs.NtfAddCuriosForSelect ntf_add_curios_for_select = 1226;
    ghs.ReqChooseEventOption req_choose_event_option = 1301;
    ghs.ResChooseEventOption res_choose_event_option = 1302;
    ghs.NtfEventInfo ntf_event_info = 1303;
    ghs.NtfMissionInfo ntf_mission_info = 1401;
    ghs.NtfMissionResult ntf_mission_result = 1402;
    ghs.ReqBag req_bag = 2001;
    ghs.ResBag res_bag = 2002;
    ghs.ReqUseItem req_use_item = 2003;
    ghs.ResUseItem res_use_item = 2004;
    ghs.ReqWeaponLevelUp req_weapon_level_up = 2005;
    ghs.ResWeaponLevelUp res_weapon_level_up = 2006;
    ghs.ReqWeaponLevelBreak req_weapon_level_break = 2007;
    ghs.ResWeaponLevelBreak res_weapon_level_break = 2008;
    ghs.ReqWeaponRefine req_weapon_refine = 2009;
    ghs.ResWeaponRefine res_weapon_refine = 2010;
    ghs.ReqArmLevelUp req_arm_level_up = 2011;
    ghs.ResArmLevelUp res_arm_level_up = 2012;
    ghs.ReqArmLevelBreak req_arm_level_break = 2013;
    ghs.ResArmLevelBreak res_arm_level_break = 2014;
    ghs.ReqItemLock req_item_lock = 2015;
    ghs.ResItemLock res_item_lock = 2016;
    ghs.ReqItemUnlock req_item_unlock = 2017;
    ghs.ResItemUnlock res_item_unlock = 2018;
    ghs.ReqItemSynthetic req_item_synthetic = 2019;
    ghs.ResItemSynthetic res_item_synthetic = 2020;
    ghs.ReqItemDecompose req_item_decompose = 2021;
    ghs.ResItemDecompose res_item_decompose = 2022;
    ghs.ReqArmForge req_arm_forge = 2023;
    ghs.ResArmForge res_arm_forge = 2024;
    ghs.NtfItemInfo ntf_item_info = 2025;
    ghs.NtfBagInfo ntf_bag_info = 2026;
    ghs.ReqCharacterList req_character_list = 3001;
    ghs.ResCharacterList res_character_list = 3002;
    ghs.ReqCharacterLevelUp req_character_level_up = 3003;
    ghs.ResCharacterLevelUp res_character_level_up = 3004;
    ghs.ReqCharacterLevelBreak req_character_level_break = 3005;
    ghs.ResCharacterLevelBreak res_character_level_break = 3006;
    ghs.ReqCharacterSkillLevelUp req_character_skill_level_up = 3007;
    ghs.ResCharacterSkillLevelUp res_character_skill_level_up = 3008;
    ghs.ReqCharacterEquipWeapon req_character_equip_weapon = 3009;
    ghs.ResCharacterEquipWeapon res_character_equip_weapon = 3010;
    ghs.ReqCharacterSwapWeapon req_character_swap_weapon = 3011;
    ghs.ResCharacterSwapWeapon res_character_swap_weapon = 3012;
    ghs.ReqCharacterEquipArm req_character_equip_arm = 3013;
    ghs.ResCharacterEquipArm res_character_equip_arm = 3014;
    ghs.ReqCharacterUnequipArm req_character_unequip_arm = 3015;
    ghs.ResCharacterUnequipArm res_character_unequip_arm = 3016;
    ghs.ReqCharacterSwapArm req_character_swap_arm = 3017;
    ghs.ResCharacterSwapArm res_character_swap_arm = 3018;
    ghs.ReqCharacterUnlockTalent req_character_unlock_talent = 3019;
    ghs.ResCharacterUnlockTalent res_character_unlock_talent = 3020;
    ghs.ReqCharacterChangeSkin req_character_change_skin = 3021;
    ghs.ResCharacterChangeSkin res_character_change_skin = 3022;
    ghs.NtfCharacterInfo ntf_character_info = 3023;
    ghs.ReqShopList req_shop_list = 4001;
    ghs.ResShopList res_shop_list = 4002;
    ghs.ReqShopRefresh req_shop_refresh = 4003;
    ghs.ResShopRefresh res_shop_refresh = 4004;
    ghs.ReqShopBuy req_shop_buy = 4005;
    ghs.ResShopBuy res_shop_buy = 4006;
    ghs.NtfShopInfo ntf_shop_info = 4007;
    ghs.ReqActivityList req_activity_list = 5001;
    ghs.ResActivityList res_activity_list = 5002;
    ghs.NtfActivityList ntf_activity_list = 5003;
    ghs.ReqActivitySign req_activity_sign = 5004;
    ghs.ResActivitySign res_activity_sign = 5005;
    ghs.ReqPlot req_plot = 6001;
    ghs.ResPlot res_plot = 6002;
    ghs.ReqPlayPlotNode req_play_plot_node = 6003;
    ghs.ResPlayPlotNode res_play_plot_node = 6004;
    ghs.ReqCompletePlotMission req_complete_plot_mission = 6005;
    ghs.ResCompletePlotMission res_complete_plot_mission = 6006;
    ghs.ReqReceivePlotTreeAward req_receive_plot_tree_award = 6007;
    ghs.ResReceivePlotTreeAward res_receive_plot_tree_award = 6008;
    ghs.NtfAddPlotMission ntf_add_plot_mission = 6009;
    ghs.ReqUnlockStoryLine req_unlock_story_line = 6101;
    ghs.ResUnlockStoryLine res_unlock_story_line = 6102;
    ghs.ReqHome req_home = 7001;
    ghs.ResHome res_home = 7002;
    ghs.ReqBuildHome req_build_home = 7003;
    ghs.ResBuildHome res_build_home = 7004;
    ghs.ReqReceiveFurnitureCoinFromInteract req_receive_furniture_coin_from_interact = 7005;
    ghs.ResReceiveFurnitureCoinFromInteract res_receive_furniture_coin_from_interact = 7006;
    ghs.ReqMailList req_mail_list = 8001;
    ghs.ResMailList res_mail_list = 8002;
    ghs.ReqMailRead req_mail_read = 8003;
    ghs.ResMailRead res_mail_read = 8004;
    ghs.ReqMailReceive req_mail_receive = 8005;
    ghs.ResMailReceive res_mail_receive = 8006;
    ghs.NtfMailList ntf_mail_list = 8007;
    ghs.ReqHardLevel req_hard_level = 9001;
    ghs.ResHardLevel res_hard_level = 9002;
    ghs.ReqHardLevelFight req_hard_level_fight = 9003;
    ghs.ResHardLevelFight res_hard_level_fight = 9004;
    ghs.ReqCompleteHardLevelFight req_complete_hard_level_fight = 9005;
    ghs.ResCompleteHardLevelFight res_complete_hard_level_fight = 9006;
    ghs.ReqTotalWar req_total_war = 10001;
    ghs.ResTotalWar res_total_war = 10002;
    ghs.ReqTotalWarFight req_total_war_fight = 10003;
    ghs.ResTotalWarFight res_total_war_fight = 10004;
    ghs.ReqCompleteTotalWarFight req_complete_total_war_fight = 10005;
    ghs.ResCompleteTotalWarFight res_complete_total_war_fight = 10006;
    ghs.ReqTotalWarRank req_total_war_rank = 10007;
    ghs.ResTotalWarRank res_total_war_rank = 10008;
    ghs.ReqReceiveTotalWarReward req_receive_total_war_reward = 10009;
    ghs.ResReceiveTotalWarReward res_receive_total_war_reward = 10010;
    ghs.NtfTotalWarAddReward ntf_total_war_add_reward = 10011;
    ghs.ReqGacha req_gacha = 11001;
    ghs.ResGacha res_gacha = 11002;
    ghs.ReqGachaCreate req_gacha_create = 11003;
    ghs.ResGachaCreate res_gacha_create = 11004;
    ghs.ReqGachaConfirm req_gacha_confirm = 11005;
    ghs.ResGachaConfirm res_gacha_confirm = 11006;
    ghs.ReqGachaDing req_gacha_ding = 11007;
    ghs.ResGachaDing res_gacha_ding = 11008;
    ghs.ReqGachaChooseCard req_gacha_choose_card = 11009;
    ghs.ResGachaChooseCard res_gacha_choose_card = 11010;
    ghs.ReqCreateOrder req_create_order = 12001;
    ghs.ResCreateOrder res_create_order = 12002;
    ghs.ReqFinishOrder req_finish_order = 12003;
    ghs.ResFinishOrder res_finish_order = 12004;
    ghs.NtfFinishOrder ntf_finish_order = 12005;
    ghs.ReqMallList req_mall_list = 13001;
    ghs.ResMallList res_mall_list = 13002;
    ghs.ReqMallBuy req_mall_buy = 13003;
    ghs.ResMallBuy res_mall_buy = 13004;
    ghs.ReqMallReceiveMonthCard req_mall_receive_month_card = 13005;
    ghs.ResMallReceiveMonthCard res_mall_receive_month_card = 13006;
    ghs.ReqMallReceiveChargePointReward req_mall_receive_charge_point_reward = 13007;
    ghs.ResMallReceiveChargePointReward res_mall_receive_charge_point_reward = 13008;
    ghs.NtfMallInfo ntf_mall_info = 13009;
    ghs.ReqGmCmd req_gm_cmd = 65301;
    ghs.ResGmCmd res_gm_cmd = 65302;
    ghs.ReqPing req_ping = 65401;
    ghs.ResPing res_ping = 65402;
    ghs.NtfMsgKey ntf_msg_key = 65403;
    ghs.NtfKick ntf_kick = 65404;
    ghs.NtfServerError ntf_server_error = 65405;
    ghs.NtfServerTime ntf_server_time = 65406;
    ghs.ReqRegister req_register = 65501;
    ghs.ResRegister res_register = 65502;
    ghs.ReqLogin req_login = 65503;
    ghs.ResLogin res_login = 65504;
    ghs.ReqRelogin req_relogin = 65505;
    ghs.ResRelogin res_relogin = 65506;
  }
}
