// Reconstructed from proto.pb (Nornium/GHS client server_info.proto)
syntax = "proto3";
package ghs;

enum ServerError {
  SERVER_ERROR_NONE = 0;
  SERVER_ERROR_REQ_AGENTMGR_FAILED = 256;
  SERVER_ERROR_CONFIG_ERROR = 257;
  SERVER_ERROR_MISSING_REQ_DATA = 258;
  SERVER_ERROR_UUID_4096 = 259;
  SERVER_ERROR_MISSING_LOADED_DATA = 260;
  SERVER_ERROR_LOAD_DATA_ERROR = 261;
  SERVER_ERROR_INTERNAL_ERROR = 262;
  SERVER_ERROR_CHECK_CONDITION_FAILED = 263;
  SERVER_ERROR_STATE_INVALID = 264;
  SERVER_ERROR_CALL_FUNC = 265;
  SERVER_ERROR_PROTO_MISMATCH = 266;
  SERVER_ERROR_MAINTENANCE = 267;
  SERVER_ERROR_TOO_FREQUENT_REQUEST = 268;
}

message NtfServerError {
}

message NtfServerTime {
  uint64 server_seconds = 1;
}
